pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building the Code .... "
            }
        }

        stage('Test') {
            steps {
                echo "Testing the Code .... "
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying the Code .... "
            }
        }
    }
}
