pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building the Code .... "
                sh "mvn clean package"
            }
            post {
              success {
                 archiveArtifacts artifacts: '**/target/*.war'
                  }
                }
        }

        stage('Test') {
            steps {
                echo "Testing the Code .... "
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying the Code .... "
            }
        }
    }
}
