pipeline {
    agent any

    tools {
      maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                echo "Building the Code .... "
                sh "mvn clean package"
            }
            post {
              success {
                 archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                  }
                }
        }

          stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
